#!/bin/bash

# In production this will be in a local directory
releaser=$(readlink -f src/releaser)
source ${releaser}

set -e
command="$1"
case "${command}" in
  set_version)
      releaser::bump_changelog_and_oversion "$2"
      exit $?
      ;;
  verify_version)
      releaser::verify_version_for_release
      exit $?
      ;;
  unit)
      time bats ./test/unit/*.bats
      exit $?
      ;;
  itest)
      time bats ./test/integration/*.bats
      exit $?
      ;;
  release)
      releaser::verify_version_for_release
      releaser::git_tag_from_oversion
      exit $?
      ;;
  publish)
      # publish the just released version
      version=$(releaser::get_last_git_tagged_version)
      releaser::publish_to_archive "releaser" "${version}" "src/releaser"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
