#!/bin/bash

# In production this will be in a local directory
releaser=$(readlink -f src/releaser)
source ${releaser}

set -e
command="$1"
case "${command}" in
  set_version)
      releaser::bump_changelog_version "$2" "$3"
      ;;
  verify_version)
      releaser::verify_version_for_release
      ;;
  unit)
      time bats ./test/unit/*.bats
      ;;
  itest)
      time bats ./test/integration/*.bats
      ;;
  release)
      releaser::verify_version_for_release
      releaser::git_tag_from_oversion
      ;;
  publish)
      # publish the just released version
      version=$(releaser::get_last_git_tagged_version)
      echo "Not impl"
      exit 2
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
