#!/bin/bash

# In production this will be in a local directory
releaser=$(readlink -f src/releaser)
source ${releaser}

set -e
command="$1"
case "${command}" in
  set_version)
      releaser::bump_changelog_version "$2" "$3"
      ;;
  verify_version)
      releaser::verify_version_for_release
      ;;
  unit)
      time bats ./test/unit/*.bats
      ;;
  itest)
      time bats ./test/integration/*.bats
      ;;
  test)
      ./tasks unit
      ./tasks itest
      ;;
  release)
      releaser::verify_version_for_release
      releaser::git_tag_from_changelog
      ;;
  publish)
      # publish the just released version
      GITHUB_TOKEN=$(vault read -field=token secret/gocd/github_releases)
      export GITHUB_TOKEN
      VERSION=$(releaser::get_last_git_tagged_version)
      releaser::prepare_github_release_bin
      $GHRELEASE_BIN release \
        --user kudulab \
        --repo releaser \
        --tag $VERSION \
        --name $VERSION \
        --pre-release

      $GHRELEASE_BIN upload \
        --user kudulab \
        --repo releaser \
        --tag $VERSION \
        --name "releaser" \
        --file src/releaser
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
