#!/bin/bash

set -e
releaser=$(readlink -f ../../../../src/releaser)
source ${releaser}
releaser_init

command="$1"
case "${command}" in
  bump)
      bump_changelog_and_oversion "$2"
      exit $?
      ;;
  bump_old)
      ide_docker_image_bump_old "$2"
      exit $?
      ;;
  verify_version)
      verify_version_in_changelog_matches_in_oversion
      verify_version_not_released_before
      exit $?
      ;;
  verify_version_for_release)
      # this task is for testing purposes only, do not treat as example
      verify_version_for_release
      exit $?
      ;;
  release)
      verify_version_for_release
      git_tag_from_oversion
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
