#!/bin/bash

set -e
releaser=$(readlink -f ../../../../src/releaser)
source ${releaser}

command="$1"
case "${command}" in
  set_version)
      releaser::bump_changelog_version "${2}" "${3}"
      exit $?
      ;;
  verify_version)
      releaser::verify_version_not_released_before
      exit $?
      ;;
  verify_version_for_release)
      # this task is for testing purposes only, do not treat as example
      releaser::verify_version_for_release
      exit $?
      ;;
  release)
      releaser::verify_version_for_release
      releaser::git_tag_from_changelog
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
