#!/bin/bash

set -Eeo pipefail

RELEASER_LOG_LEVEL=${RELEASER_LOG_LEVEL:-info}
dryrun="${dryrun:-false}"
changelog_file="${changelog_file:-CHANGELOG.md}"

RELEASER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

################################################################################
# Generally:
# * Each log output goes to stderrr, so that we can return value from functions
# with stdout. (Curl does the same).
################################################################################

releaser::program_name() {
  echo "RELEASER"
}
# obsolete function
releaser_program_name() {
  releaser::program_name
}
releaser::log_debug() {
  if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
    echo -e "$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) debug: ${1}" >&2
  fi
}
releaser::log_info() {
  echo -e "$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) info: ${1}" >&2
}
releaser::log_error() {
  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) error: $1\e[0m" >&2
  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
}
releaser::log_warn() {
  echo -e "\e[33m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser::program_name) warn: $1\e[0m" >&2
}

# In order to load all the releaser functions once you can run:
# releaser::loaded || eval "$(curl http://gogs.ai-traders.com/platform/releaser/raw/0.2.0/src/releaser)"
# Or you can simply wget that file and source it.
function releaser::loaded {
  return 0
}
# Arguments:
#   changelog_file
function releaser::get_last_version_from_changelog {
  local changelog_file="${1:-CHANGELOG.md}"
  if [[ ! -f "${changelog_file}" ]];then
    releaser::log_error "${changelog_file} does not exist"
    return 1
  fi
  version=$(cat $changelog_file | head -1 | grep -o -e "[0-9]*\.[0-9]*\.[0-9]*")
  if [[ "${version}" == "" ]];then
    releaser::log_error "Could not get last version from ${changelog_file}"
    return 1
  fi
  echo "${version}"
}

# This function exists, because in bash: return in the while loop scope
# does not exit the whole function.
function releaser::get_last_version_from_changelog_inner {
  local changelog_file="${1:-CHANGELOG.md}"
  cat ${changelog_file} | \
  while read line; do
      version=$(echo "${line}" | grep -o -e "# [0-9]*\.[0-9]*\.[0-9]*" | grep -o -e "[0-9]*\.[0-9]*\.[0-9]*")
      if [[ "${version}" != "" ]];then
        echo "${version}"
        return 0
      fi
  done
}

# Reads the changelog file line by line, finds the first line that
# matches version pattern and returns the version.
# Arguments:
#   changelog_file
function releaser::get_last_version_from_whole_changelog {
  local changelog_file="${1:-CHANGELOG.md}"
  if [[ ! -f "${changelog_file}" ]];then
    releaser::log_error "${changelog_file} does not exist"
    return 1
  fi
  version="$(releaser::get_last_version_from_changelog_inner ${changelog_file})"
  if [[ "${version}" == "" ]];then
    releaser::log_error "No line in ${changelog_file} matches version pattern! (# [0-9]*\.[0-9]*\.[0-9]*)"
    return 1
  fi
  echo "${version}"
}
# Arguments: none
function releaser::get_last_git_tagged_version {
  set +Ee
  tag="$(git tag 2>&1 | sort -V | tail -1)"
  if [[ "${tag}" == *"Not a git repository"* ]];then
    releaser::log_error "Not a git repository"
    return 1
  fi
  set -Ee
  echo "${tag}"
}
function releaser::git_tag_from_changelog {
  new_version="$(releaser::get_last_version_from_changelog)"
  git tag "${new_version}" && git push origin "${new_version}"
}
# Given the old_version in a SemVer format, e.g. 0.1.2, returns new version
# with patch fragment increased by 1, e.g. 0.1.3.
# Arguments:
#   old_version
function releaser::bump_patch_version {
  local old_version="${1?old_version not set}"
  releaser::log_debug "Validating old_version"
  releaser::validate_version_is_semver "${old_version}"
  exit_status="$?"
  if [[ "${exit_status}" != 0 ]]; then
    return "${exit_status}"
  fi

  #replace . with space so can split into an array
  version_bits=(${old_version//./\ })
  major=${version_bits[0]}
  minor=${version_bits[1]}
  patch=${version_bits[2]}

  patch=$((patch+1))
  echo "${major}.${minor}.${patch}"
}
# Arguments:
#   * version
function releaser::validate_version_is_semver {
  local version="${1?version not set}"
  if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
    releaser::log_error "Version was not SemVer. It was: ${version}. Must be e.g. 0.1.2"
    return 1
  fi
}

# Replaces the whole line in a version file with that line and adds new version.
# Arguments:
#   line_pattern
#   new_version
#   version_file
function releaser::set_version_in_file {
  local line_pattern="${1?line_pattern not set}"
  local version_file="${2?version_file not set}"
  local new_version="${3?new_version not set}"
  if [[ ! -f "${version_file}" ]];then
    releaser::log_error "${version_file} does not exist"
    return 1
  fi
  new_versionfile_contents=$(sed "s/${line_pattern}.*/${line_pattern}\"${new_version}\"/g" ${version_file})
  releaser::log_debug "Will replace version file with:"
  releaser::log_debug "${new_versionfile_contents}"
  if [[ "${dryrun}" != "true" ]];then
    echo "${new_versionfile_contents}" > "${version_file}"
  fi
}

# Takes care of the first line of changelog file.
# There are various cases supported. Suppose we bump to 0.2.0:
#   Case 1 - changelog 1st line contains older version header or no header
#     ### 0.1.0 (2017-Apr-29)
#     Becomes:
#     ### 0.2.0 (2017-Apr-30)
#     ### 0.1.0 (2017-Apr-29)
#   Case 2 - changelog 1st line contains the same version header
#     ### 0.2.0 (2017-Apr-30)
#     Becomes: (no changes, even if date is different)
#     ### 0.2.0 (2017-Apr-30)
#   Case 3 - changelog 1st line contains Unreleased and the same version header:
#     ### 0.2.0 - Unreleased
#     Becomes:
#     ### 0.2.0 (2017-Apr-29)
#   Case 4 - changelog 1st line contains Unreleased and older version header:
#     ### 0.1.0 - Unreleased
#     Becomes:
#     ### 0.2.0 (2017-Apr-29)
#
# Arguments:
#   new_version
#   changelog_file
function releaser::set_version_in_changelog {
  local changelog_file="${1:-CHANGELOG.md}"
  local new_version="${2?new_version not set}"
  local unreleased="${3}"

  if [[ ! -f "${changelog_file}" ]];then
    releaser::log_error "${changelog_file} does not exist"
    return 1
  fi

  if [[ -n "$unreleased" ]]; then
    new_line="### ${new_version} - Unreleased"
  else
    release_date=$(LANG=en_US date +%Y-%b-%d)
    new_line="### ${new_version} (${release_date})"
  fi

  changelog_first_line=$(cat ${changelog_file} | head -1)
  if [[ ! -z "$unreleased" ]] && [[ "${changelog_first_line}" == "### ${new_version} - Unreleased"* ]];then
    # idempotent
    releaser::log_debug "Version and unreleased flag in changelog is already set"
    return 0
  elif [[ -z "$unreleased" ]] && [[ "${changelog_first_line}" == "### ${new_version} ("* ]];then
    # idempotent
    releaser::log_debug "Version in changelog is already set"
    return 0
  elif [[ "${changelog_first_line}" == "### "*"Unreleased" ]];then
    releaser::log_debug "Changing current unreleased head of changelog"
    changelog_tail=$(tail -n +2 ${changelog_file})
    if [[ "${dryrun}" != "true" ]];then
      echo "${new_line}" > "${changelog_file}"
      echo "${changelog_tail}" >> "${changelog_file}"
    fi
    return $?
  else
    releaser::log_debug "Will add new line to changelog:"
    releaser::log_debug "${new_line}"
    if [[ "${dryrun}" != "true" ]];then
      old_changelog=$(cat "${changelog_file}")
      echo "${new_line}" > "${changelog_file}"
      echo "" >> "${changelog_file}"
      echo "${old_changelog}" >> "${changelog_file}"
      return $?
    fi
  fi
}

################################################################################
# The End user functions here:
#  * use default values set in the bottom of releaser
################################################################################

# Test that the version was not already released.
function releaser::verify_version_not_released_before {
  version_from_changelog=$(releaser::get_last_version_from_changelog "${changelog_file}")
  if git tag | grep "${version_from_changelog}"; then
    releaser::log_error "The last version from changelog was already git tagged: ${version_from_changelog}"
    exit 1
  fi
  releaser::log_info "Version was not released before"
}
# This function should be used in any project that does not use version file,
# e.g. ide docker image.
function releaser::verify_version_for_release {
  releaser::verify_version_not_released_before
  changelog_first_line=$(cat ${changelog_file} | head -1)
  if [[ "${changelog_first_line}" == "#"*"Unreleased"* ]] || [[ "${changelog_first_line}" == "#"*"unreleased"* ]] || [[ "${changelog_first_line}" == "#"*"UNRELEASED"* ]];then
    releaser::log_error "Top of changelog has 'Unreleased' flag"
    exit 1
  fi
  releaser::log_info "Version verified successfully"
}

function releaser::verify_changelog_version {
  version=$(releaser::get_last_version_from_changelog "${changelog_file}")
  if git tag | grep "${version}"; then
    releaser::log_error "The last version from changelog was already git tagged: ${version}"
    exit 1
  fi
  releaser::validate_version_is_semver "${version}"
  changelog_first_line=$(cat ${changelog_file} | head -1)
  if [[ "${changelog_first_line}" == "#"*"Unreleased"* ]] || [[ "${changelog_first_line}" == "#"*"unreleased"* ]] || [[ "${changelog_first_line}" == "#"*"UNRELEASED"* ]];then
    releaser::log_error "Top of changelog has 'Unreleased' flag"
    exit 1
  fi
  releaser::log_info "Changelog version verified successfully"
}
# This function:
#  * bumps version in changelog: it adds a newline and a line with date
# and version number as the first lines in changelog
# You should first fill out changelog with changes history and then use this
# function.
# Arguments:
#  * new version - optional, if not set, then patch version will be bumped by 1
function releaser::bump_changelog_version {
  new_version="$1"
  unreleased="$2"
  if [[ -z "${new_version}" ]];then
    # get next_version from changelog, which was last released
    old_version="$(releaser::get_last_version_from_changelog)"
    new_version="$(releaser::bump_patch_version ${old_version})"
  fi
  releaser::log_debug "Validating new_version"
  releaser::validate_version_is_semver "${new_version}"
  releaser::log_info "New version will be: ${new_version}"
  releaser::set_version_in_changelog "${changelog_file}" "${new_version}" "${unreleased}"
  releaser::log_info "Bumped to ${new_version} in ${changelog_file}"
}

################################################################################
# Github releases
################################################################################

function releaser::prepare_github_release_bin {
  GITHUB_RELEASER_VERSION="0.7.2"

  if [ -z "$GITHUB_TOKEN" ]; then
      echo "GITHUB_TOKEN is unset";
      exit 1;
  fi
  cd $RELEASER_DIR
  if [ ! -f linux-amd64-github-release.tar.bz2 ]; then
      wget https://github.com/aktau/github-release/releases/download/v${GITHUB_RELEASER_VERSION}/linux-amd64-github-release.tar.bz2 -O linux-amd64-github-release.tar.bz2
  fi
  tar xf linux-amd64-github-release.tar.bz2
  export GHRELEASE_BIN="$RELEASER_DIR/bin/linux/amd64/github-release"
  cd -
}

################################################################################
# Common for ide k8s chart project type
################################################################################

function releaser::get_chart_version {
  local version_file="${1?version_file not set}"
  cat "${version_file}" | grep "version" | grep -o -e "[0-9]*\.[0-9]*\.[0-9]*"
}
function releaser::bump_chart_version {
  local version_file="${1?version_file not set}"
  local new_version="$2"
  if [[ -z "${new_version}" ]];then
    # get previous version from changelog
    old_version="$(releaser::get_last_version_from_changelog)"
    new_version="$(releaser::bump_patch_version ${old_version})"
  fi

  releaser::set_version_in_file "version: " "${version_file}" "${new_version}"
  releaser::log_info "Bumped to ${new_version} in ${version_file}"
}
function releaser::verify_version_not_released_chart {
  local version_file="${1?version_file not set}"

  chart_version="$(get_chart_version ${version_file})"
  if [[ $(git tag | grep "${chart_version}" -c) -ne 0 ]]; then
    echo "git tag: ${chart_version} exists already, please bump version in "\
    "${version_file}"
    exit 1
  fi
  changelog_version=$(get_last_version_from_changelog "${changelog_file}")
  if [[ $(git tag | grep "${changelog_version}" -c) -ne 0 ]]; then
    echo "git tag: ${changelog_version} exists already, please bump version in "\
    "changelog file"
    exit 1
  fi
  if [[ "${chart_version}" != "${changelog_version}" ]];then
    echo "chart_version: ${chart_version} != changelog_version: ${changelog_version}"
    exit 1
  fi
}
